title: <p align="center"> Rahul Chatterjee </p>

logo: "1687492163199,jpeg?raw=true"

description:
  <p align="center">
  <a href="Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahul-chatterjee-m-sc-878a61145/">LinkedIn</a> |
  <a href="https://github.com/RahulChatterjee07">GitHub</a>
  </p>
  
  <p align="justify">
  AI enthusiast dedicated to unlocking the potential of AI for businesses, revolutionizing industries one algorithm at a time.
  <br><br>
  As a Machine Learning Engineer at SiftMed, I develop and deploy machine learning models and algorithms to process and understand large volumes of unstructured text. I apply my skills and knowledge in natural language processing (NLP) and large language models (LLMs) to create innovative solutions for the healthcare industry. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
