title: <p align="center"> Rahul Chatterjee </p>

logo: "ProfilePicture.png?raw=true"

description:
  <p align="center">
  <a href="Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahul-chatterjee-878a61145/">LinkedIn</a> |
  <a href="https://github.com/RahulChatterjee07">GitHub</a>
  </p>
  
  <p align="justify">
  Self-motivated data science enthusiast, passionate about applying various machine learning algorithms to solve real-world problems.
  <br><br>
  I am currently working as a graduate research assistant in Bio signals and Systems Analysis Lab in collaboration with CRIR research center, Montreal.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
